name: Agent CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (basic)
        run: python -m py_compile $(git ls-files '*.py')
      - name: Run smoke tests
        run: |
          python - <<'PY'
import importlib
import sys
mods = ['app.main','app.models','app.schemas']
for m in mods:
    importlib.import_module(m)
print('ok')
PY
